/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 4;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 5;
  /** RegularExpression Id. */
  int CONSTANT = 6;
  /** RegularExpression Id. */
  int VARIABLE = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int MULTIPLY = 10;
  /** RegularExpression Id. */
  int DIVIDE = 11;
  /** RegularExpression Id. */
  int LESS_THAN = 12;
  /** RegularExpression Id. */
  int MORE_THAN = 13;
  /** RegularExpression Id. */
  int EQUAL = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int END = 17;
  /** RegularExpression Id. */
  int OPERATOR = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "<CONSTANT>",
    "<VARIABLE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"while\"",
    "\"if\"",
    "\"end\"",
    "<OPERATOR>",
  };

}
